In [71]:
import pandas as pd
import numpy as np
import statistics

In [72]:
df=pd.read_excel('C:/Users/LENOVO/Downloads/Mission stocks/All data/MISSION STOCKS.xlsx')

In [73]:
df.head(2)

,Date,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BHARTIARTL,BPCL,BRITANNIA,...,PEL,PETRONET,PIDILITIND,PNB,UBL,TORNTPHARM,SIEMENS,SBICARD,PGHH,Unnamed: 99
0,2021-07-09,728.5,3010.6,747.35,3995.9,12854.75,6136.15,536.25,456.9,3475.95,...,2312.15,224.0,2277.80,41.00,1431.35,3005.05,2002.15,974.5,13134.70,NaN
1,2021-07-08,711.7,3028.3,754.40,4077.3,12333.90,6117.80,525.30,458.2,3491.40,...,2320.45,223.8,2283.45,41.05,1420.20,2945.50,2013.45,984.4,13186.95,NaN

In [74]:
df.head(1)

,Date,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BHARTIARTL,BPCL,BRITANNIA,...,PEL,PETRONET,PIDILITIND,PNB,UBL,TORNTPHARM,SIEMENS,SBICARD,PGHH,Unnamed: 99
0,2021-07-09,728.5,3010.6,747.35,3995.9,12854.75,6136.15,536.25,456.9,3475.95,...,2312.15,224.0,2277.8,41.0,1431.35,3005.05,2002.15,974.5,13134.7,NaN

In [75]:
df.shape

(252, 100)

In [76]:
cols=df.columns
cols=cols[1:-1]
print(cols)

Index(['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV',
       'BAJFINANCE', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA',
       'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFC',
       'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR',
       'ICICIBANK', 'INDUSINDBK', 'INFY', 'IOC', 'ITC', 'JSWSTEEL',
       'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC',
       'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SHREECEM', 'SUNPHARMA',
       'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN',
       'ULTRACEMCO', 'UPL', 'WIPRO', 'ABBOTINDIA', 'ACC', 'ADANIENT', 'ALKEM',
       'AMBUJACEM', 'APOLLOHOSP', 'AUROPHARMA', 'BAJAJHLDNG', 'BANDHANBNK',
       'BERGEPAINT', 'BIOCON', 'BOSCHLTD', 'CADILAHC', 'COLPAL', 'DABUR',
       'DLF', 'DMART', 'GAIL', 'GLAND', 'GODREJCP', 'HDFCAMC', 'HINDPETRO',
       'ICICIGI', 'HAVELLS', 'ICICIPRULI', 'IGL', 'INDIGO', 'INDUSTOWER',
       'YESBANK', 'VEDL', 'JUBLFOOD', 'LTI', 'LUPIN', 'MARICO', 'MCDOWELL-N',
       'MRF', 'MUTHOOTFIN', 'NAUKRI', 'NMDC', 'PEL', 'PETRONET', 'PIDILITIND',
       'PNB', 'UBL', 'TORNTPHARM', 'SIEMENS', 'SBICARD', 'PGHH'],
      dtype='object')

In [77]:
df_dict={}
for col in cols:
    rt=[]
    for i in range(len(df[col])-1):
        num=df[col].iloc[i+1]
        den=df[col].iloc[i]
        val=np.log(num/den)
        val_final=val*100
        rt.append(val_final)

    average=statistics.mean(rt)
    std=statistics.stdev(rt)
#     print("Average is ",col ," is ",average)
#     print("Standard deviation is ",col ," is ",std)
#     print("upper 1 avg+std is ",average+std)
#     print("lower 1 avg-std is ",average-std)
#     print("upper 2 avg+2std is ",average+(2*std))
#     print("lower 2 avg-2std is ",average-(2*std))
    df_dict[col]=[average+std,average-std,average+(2*std),average-(2*std)]

In [78]:
# statistics.mean(rt)

In [79]:
# for i in range(len(rt)):
#     rt[i]=rt[i]*100

In [80]:
# len(rt)

In [81]:
# tot=0
# length=len(rt)
# for i in rt:
#     tot=tot+i
# print(tot/length)

In [82]:
df_dict

{'ADANIPORTS': [2.283528778629008,
  -2.8833853174980257,
  4.866985826692525,
  -5.466842365561543],
 'ASIANPAINT': [1.5325832226318554,
  -1.9799260276776036,
  3.288837847786585,
  -3.736180652832333],
 'AXISBANK': [2.1362870463973103,
  -2.533886433371624,
  4.471373786281777,
  -4.868973173256091],
 'BAJAJ-AUTO': [1.510727149291128,
  -1.7711130758814244,
  3.1516472618774043,
  -3.4120331884677007],
 'BAJAJFINSV': [1.9631961296587621,
  -2.4981135267597576,
  4.193850957868022,
  -4.728768354969017],
 'BAJFINANCE': [2.1330587103906407,
  -2.6200907467786063,
  4.509633438975264,
  -4.99666547536323],
 'BHARTIARTL': [1.9521908977396714,
  -1.9054461484263427,
  3.881009420822678,
  -3.83426467150935],
 'BPCL': [2.0816279002849303,
  -2.235319303522078,
  4.240101502188435,
  -4.393792905425582],
 'BRITANNIA': [1.3143806177857194,
  -1.270313458619829,
  2.6067276559884935,
  -2.562660496822603],
 'CIPLA': [1.6824035285358916,
  -2.0065009236326428,
  3.526855754620159,
  -3.85095314971691],
 'COALINDIA': [1.914345613720758,
  -2.0081966381481555,
  3.875616739655215,
  -3.9694677640826126],
 'DIVISLAB': [1.5922108624835085,
  -2.188499246809669,
  3.4825659171300973,
  -4.078854301456257],
 'DRREDDY': [1.6315441943296798,
  -1.90038830211668,
  3.3975104425528597,
  -3.66635455033986],
 'EICHERMOT': [15.43971080203845,
  -13.868544711362974,
  30.09383855873916,
  -28.522672468063686],
 'GRASIM': [1.5445428518600834,
  -2.252924349930712,
  3.443276452755481,
  -4.15165795082611],
 'HCLTECH': [1.6196608116124416,
  -2.0237891633496305,
  3.441385799093478,
  -3.8455141508306667],
 'HDFC': [1.8363914778792627,
  -2.0365736259203304,
  3.772874029779059,
  -3.973056177820127],
 'HDFCBANK': [1.6406365855179192,
  -1.8709624525439654,
  3.3964361045488616,
  -3.6267619715749078],
 'HDFCLIFE': [1.3955302126724864,
  -1.5189622092160773,
  2.8527764236167683,
  -2.976208420160359],
 'HEROMOTOCO': [1.762669447166951,
  -1.8212563775451558,
  3.5546323595230045,
  -3.613219289901209],
 'HINDALCO': [2.2832174832550205,
  -2.9697053864892444,
  4.9096789181271525,
  -5.596166821361377],
 'HINDUNILVR': [1.220036830681543,
  -1.3150649529372544,
  2.4875877224909417,
  -2.582615844746653],
 'ICICIBANK': [2.018119531316024,
  -2.4521844528164007,
  4.253271523382237,
  -4.687336444882613],
 'INDUSINDBK': [2.733218323364176,
  -3.2313624668839966,
  5.7155087184882625,
  -6.213652862008082],
 'INFY': [1.3223174013162362,
  -1.8743710376683183,
  2.9206616208085134,
  -3.4727152571605955],
 'IOC': [1.7527777731148158,
  -1.9244783593290147,
  3.591405839336731,
  -3.7631064255509297],
 'ITC': [1.4945356774802896,
  -1.5182329643794916,
  3.00091999841018,
  -3.0246172853093825],
 'JSWSTEEL': [1.7827492383039842,
  -2.769907985940791,
  4.059077850426372,
  -5.046236598063179],
 'KOTAKBANK': [1.79304959711762,
  -1.9754351731002078,
  3.6772919822265338,
  -3.8596775582091216],
 'LT': [1.5598319118154655,
  -1.927817305298104,
  3.3036565203722503,
  -3.671641913854889],
 'M&M': [2.0689395940076176,
  -2.3238631987454452,
  4.265340990384149,
  -4.520264595121977],
 'MARUTI': [1.5918096637532737,
  -1.7613681475189904,
  3.2683985693894058,
  -3.4379570531551225],
 'NESTLEIND': [1.3067484908261364,
  -1.3473866367764327,
  2.6338160546274207,
  -2.6744542005777174],
 'NTPC': [1.8337175788853293,
  -2.0376485542934573,
  3.769400645474722,
  -3.9733316208828504],
 'ONGC': [2.1777350325204883,
  -2.48475757648133,
  4.508981337021397,
  -4.816003880982239],
 'POWERGRID': [1.738855356874707,
  -1.9733501025567446,
  3.5949580865904327,
  -3.8294528322724704],
 'RELIANCE': [1.8108187614118894,
  -1.9119814751900557,
  3.672218879712862,
  -3.773381593491028],
 'SBILIFE': [1.4137957128683694,
  -1.567952052228325,
  2.9046695954167165,
  -3.058825934776672],
 'SBIN': [2.0536090692850504,
  -2.6554707805396394,
  4.408148994197395,
  -5.010010705451984],
 'SHREECEM': [1.8412175269195215,
  -1.9905144045607044,
  3.7570834926596346,
  -3.906380370300817],
 'SUNPHARMA': [1.658954134950136,
  -1.9189526110470383,
  3.4479075079487234,
  -3.707905984045625],
 'TATACONSUM': [1.5735109319355074,
  -2.027352507934194,
  3.373942651870358,
  -3.827784227869045],
 'TATAMOTORS': [2.664980639818069,
  -3.50338986556334,
  5.749165892508774,
  -6.587575118254044],
 'TATASTEEL': [2.036066609966608,
  -3.056184727225183,
  4.582192278562503,
  -5.602310395821079],
 'TCS': [1.3453657624293878,
  -1.6443791219155113,
  2.840238204601837,
  -3.139251564087961],
 'TECHM': [1.5718382280278036,
  -2.049805288110467,
  3.382659986096939,
  -3.860627046179603],
 'TITAN': [1.5472646995130612,
  -1.986756700350533,
  3.3142753994448584,
  -3.7537674002823302],
 'ULTRACEMCO': [1.5055081953446527,
  -1.9717120131445927,
  3.2441182995892754,
  -3.7103221173892154],
 'UPL': [2.249018481273116,
  -2.7351398845378903,
  4.741097664178619,
  -5.227219067443394],
 'WIPRO': [1.7444724021274958,
  -2.432956033539967,
  3.8331866199612272,
  -4.521670251373698],
 'ABBOTINDIA': [1.1478129048123866,
  -1.2305592823173817,
  2.336998998377271,
  -2.4197453758822656],
 'ACC': [1.5455110583352833,
  -1.895479269757889,
  3.2660062223818693,
  -3.6159744338044755],
 'ADANIENT': [2.545256530459856,
  -4.277653385255696,
  5.956711488317632,
  -7.689108343113471],
 'ALKEM': [1.4761853123805808,
  -1.7344659514527254,
  3.081510944297234,
  -3.3397915833693785],
 'AMBUJACEM': [1.68360626409564,
  -2.1519621723841813,
  3.6013904823355505,
  -4.069746390624092],
 'APOLLOHOSP': [1.872876788441112,
  -2.6505525874713785,
  4.1345914763973575,
  -4.912267275427624],
 'AUROPHARMA': [1.999789168818783,
  -2.122884408377592,
  4.06112595741697,
  -4.18422119697578],
 'BAJAJHLDNG': [1.5577261737963892,
  -1.8016607944803893,
  3.2374196579347787,
  -3.4813542786187783],
 'BANDHANBNK': [2.677949829780423,
  -2.5305801176859477,
  5.282214803513608,
  -5.134845091419133],
 'BERGEPAINT': [1.2993830839734448,
  -1.7095840753163016,
  2.803866663618318,
  -3.214067654961175],
 'BIOCON': [1.9844587600125079,
  -1.949551877420313,
  3.9514640787289186,
  -3.9165571961367234],
 'BOSCHLTD': [2.104247040448248,
  -2.209193664114269,
  4.260967392729507,
  -4.365914016395527],
 'CADILAHC': [1.7929629070421824,
  -2.260833784260235,
  3.819861252693391,
  -4.2877321299114435],
 'COLPAL': [1.1805211446210353,
  -1.3571412927944015,
  2.449352363328754,
  -2.6259725115021197],
 'DABUR': [1.1274955836046794,
  -1.311055910026513,
  2.3467713304202755,
  -2.530331656842109],
 'DLF': [2.5326794091125433,
  -3.107453783286117,
  5.352746005311873,
  -5.927520379485447],
 'DMART': [1.9041658852970378,
  -2.2033271297139874,
  3.9579123928025504,
  -4.2570736372195],
 'GAIL': [2.116788917695039,
  -2.3815440574441635,
  4.36595540526464,
  -4.630710545013765],
 'GLAND': [nan, nan, nan, nan],
 'GODREJCP': [1.8333805728460761,
  -2.097165600705615,
  3.798653659621922,
  -4.06243868748146],
 'HDFCAMC': [1.5779201234829903,
  -1.705512417855334,
  3.219636394152152,
  -3.3472286885244964],
 'HINDPETRO': [1.943635912638941,
  -2.187712975498678,
  4.009310356707751,
  -4.253387419567488],
 'ICICIGI': [1.630339870223773,
  -1.7979102562619744,
  3.3444649334666465,
  -3.5120353195048484],
 'HAVELLS': [1.897065726624175,
  -2.3393332185858298,
  4.0152651992291775,
  -4.457532691190832],
 'ICICIPRULI': [1.7251072913346677,
  -2.002095982078129,
  3.5887089280410662,
  -3.865697618784528],
 'IGL': [1.8791812277296143,
  -2.1410073491823396,
  3.889275516185591,
  -4.151101637638316],
 'INDIGO': [2.2542546359483886,
  -2.710898766976527,
  4.736831337410846,
  -5.193475468438985],
 'INDUSTOWER': [2.6533913375373133,
  -2.7476755300911724,
  5.353924771351556,
  -5.448208963905415],
 'YESBANK': [3.524559638631088,
  -2.967753584304696,
  6.77071625009898,
  -6.213910195772588],
 'VEDL': [2.4889098561552405,
  -3.1946050061040516,
  5.330667287284887,
  -6.036362437233698],
 'JUBLFOOD': [1.861779796962808,
  -2.3496027386196694,
  3.9674710647540468,
  -4.455294006410909],
 'LTI': [2.2141716945092114,
  -2.745167506882411,
  4.693841295205022,
  -5.224837107578223],
 'LUPIN': [2.0373414542794612,
  -2.260886682229279,
  4.186455522533832,
  -4.410000750483649],
 'MARICO': [1.3313673296927147,
  -1.6809078004699844,
  2.837504894774064,
  -3.187045365551334],
 'MCDOWELL-N': [1.5969172109812109,
  -1.6340052201786344,
  3.2123784265611337,
  -3.2494664357585568],
 'MRF': [1.7095438019492648,
  -1.8708342340214363,
  3.4997328199346156,
  -3.6610232520067867],
 'MUTHOOTFIN': [2.167303240424258,
  -2.441276710373738,
  4.471593215823256,
  -4.745566685772736],
 'NAUKRI': [2.394933264340507,
  -2.8979839700791663,
  5.041391881550344,
  -5.544442587289002],
 'NMDC': [2.3948502761386123,
  -2.929521662125219,
  5.0570362452705275,
  -5.591707631257135],
 'PEL': [2.575157104631862,
  -2.9489420583709407,
  5.337206686133263,
  -5.710991639872343],
 'PETRONET': [1.8556642871501463,
  -1.7217329930217127,
  3.6443629272360756,
  -3.5104316331076424],
 'PIDILITIND': [1.2770038441785518,
  -1.6763656227305364,
  2.753688577633096,
  -3.1530503561850804],
 'PNB': [2.7460980803964135,
  -2.825743576086387,
  5.532018908637814,
  -5.6116644043277875],
 'UBL': [1.7749278282345615,
  -2.0066562978049878,
  3.665719891254336,
  -3.8974483608247623],
 'TORNTPHARM': [1.685768999192239,
  -1.8771915166263033,
  3.46724925710151,
  -3.658671774535575],
 'SIEMENS': [1.5230725302377695,
  -1.9686234243958138,
  3.268920507554561,
  -3.7144714017126055],
 'SBICARD': [1.9829404210358323,
  -2.2486699346289885,
  4.098745598868243,
  -4.364475112461399],
 'PGHH': [1.2973866030087198,
  -1.466506551151046,
  2.679333180088603,
  -2.8484531282309287]}

In [83]:
# statistics.stdev(rt)

In [84]:
df_final=pd.DataFrame.from_dict(df_dict, orient='index')

In [89]:
df_final=df_final.round(decimals=2)

In [90]:
df_final.columns=["upper avg+1std","lower avg-1std","upper avg+2std","lower avg-2std"]

In [91]:
df_final.head()

            upper avg+1std  lower avg-1std  upper avg+2std  lower avg-2std
ADANIPORTS            2.28           -2.88            4.87           -5.47
ASIANPAINT            1.53           -1.98            3.29           -3.74
AXISBANK              2.14           -2.53            4.47           -4.87
BAJAJ-AUTO            1.51           -1.77            3.15           -3.41
BAJAJFINSV            1.96           -2.50            4.19           -4.73

In [92]:
# df.to_csv("Data.csv")

In [93]:
df_dict["ADANIPORTS"]

[2.283528778629008, -2.8833853174980257, 4.866985826692525, -5.466842365561543]

In [95]:
df["GLAND"].isnull().sum()

95